services:
  mailhog:
    container_name: mailhog
    image: druidfi/mailhog:latest
    restart: always
    user: ${RUN_UID}:${RUN_GID}
    profiles:
      - debug
    expose:
      - 1025
      - 8025
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - network
